#!/bin/bash
########################################################
#  Script         : eog-bootstrap-salt
#  Author         : Robert Callicotte <robby_callicotte@eogresources.com>
#  Date           : 2017-08-01
#  Last Edit      : 2017-08-01
#  Summary        : Simple Bootstrapper.
#  Description    : Simple bootstrapper for deploying minions via vmware cloud connector.


